version: "3.5"
name: cover-generator
services:
  client:
    build: 
      context: .
      dockerfile: client.Dockerfile
    env_file:
      - .env
    volumes:
      - ./apps/client/dist:/usr/local/apps/client/dist
  server:
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - .env
    volumes:
      - ./images:/usr/local/apps/server/images
  db:
    restart: always
    image: postgres:16.1-bullseye
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"